### ISSUE TITLE
Replace Sprintf with text template in gen/main.go

### ISSUE THREAD

**Issue by sivachandran** [grafana/jfr-parser#34]
The Sprintfs in gen/main.go can be replaced with Go's text/template and it would improve the readability and maintainability significantly. This change won't affect the syntax or semantic of generated code.

Let me know if this improvement is welcomed, I will raise a PR with the changes. @korniltsev

**Comment by korniltsev** [comment]
I agree that the current version of code generator is not golang ideomatic and is not very readable and maintainable.
I agree that `text/template` may improve it, although it is hard to measure.
At the same time we do not need to maintain or read this code that much. 
So it looks like the proposed change is trying to solve a problem that we don't have yet.
I suggest we do no changes for now until we have to do a lot of changes in the code.
