### ISSUE TITLE
Update IDMap to use uint64

### ISSUE THREAD

**Issue by korniltsev** [grafana/jfr-parser#40]
https://github.com/grafana/jfr-parser/pull/39

**Comment by sivachandran** [comment]
As far as I searched, IDMap is only used in [MethodList](https://github.com/grafana/jfr-parser/blob/1cbe18cffc759ac584117eb57bf4be0c04a525f0/parser/types/method.go#L57). `MethodRef` already uses `uint64` which would be used as key for the `IDMap`. So I don't see a need to change anything further.

**Comment by korniltsev** [comment]
ok I'm wrong.  Sorry for confusion.
